DROP TABLE Product IF EXISTS;

CREATE TABLE Product (
  productid BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
  prodName VARCHAR(50) NOT NULL,
  price FLOAT NOT NULL,
  productType VARCHAR(30) NOT NULL,
  genre VARCHAR(50),
  author VARCHAR(50),
  publications VARCHAR(50),
  atype VARCHAR(50),
  brand VARCHAR(50),
  design VARCHAR(50),
  PRIMARY KEY(productid)
);

DROP Table User IF EXISTS;

CREATE TABLE User (
  userid BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
  username VARCHAR(50),
  address VARCHAR(50),
  pincode VARCHAR(50),
  PRIMARY KEY(userid)
);

DROP TABLE Cart IF EXISTS;

CREATE TABLE Cart (
  userid BIGINT NOT NULL,
  productid BIGINT NOT NULL,
  quantity INT,
  price FLOAT,
  PRIMARY KEY(productid, userid)
);
