DROP TABLE Product IF EXISTS;

CREATE TABLE Product (
  productid BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
  prodName VARCHAR(50) NOT NULL,
  price FLOAT NOT NULL,
  productType VARCHAR(30) NOT NULL,
  genre VARCHAR(50),
  author VARCHAR(50),
  publications VARCHAR(50),
  atype VARCHAR(50),
  brand VARCHAR(50),
  design VARCHAR(50),
  PRIMARY KEY(productid)
);

DROP Table User IF EXISTS;

CREATE TABLE User (
  userid BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
  username VARCHAR(50),
  address VARCHAR(50),
  pincode VARCHAR(50),
  PRIMARY KEY(userid)
);

DROP TABLE Cart IF EXISTS;

CREATE TABLE Cart (
  cartid BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
  userid BIGINT NOT NULL,
  PRIMARY KEY(cartid),
  UNIQUE (cartid, userid),
  FOREIGN KEY(userid) REFERENCES User(userid)
);

DROP TABLE CartProduct IF EXISTS;

CREATE TABLE CartProduct (
  cartid BIGINT NOT NULL,
  productid BIGINT NOT NULL,
  quantity INT,
  PRIMARY KEY(cartid, productid),
  FOREIGN KEY(cartid) REFERENCES Cart(cartid),
  FOREIGN KEY(productid) REFERENCES Product(productid)
);
